name: ScreenShare
version: '1.0'
main: plugin.screenshare.ScreenShare
api-version: '1.21'
commands:
  ssunfreeze:
    description: Unfreeze player
    aliases:
      - unfreeze
    permission: screenshare.unfreeze

  ssfreeze:
    description: Freeze player
    aliases:
      - freeze
    permission: screenshare.freeze


permissions:
  screenshare.freeze:
    description: Allow people to freeze others
    default: op

  screenshare.unfreeze:
    description: Allow people to unfreeze others
    default: op