name: ScreenShare
version: '1.0'
main: plugin.screenshare.ScreenShare
api-version: '1.21'
commands:
  ssunfreeze:
    description: Unfreeze player
    aliases:
      - unfreeze
    permission: screenshare.*

  ssfreeze:
    description: Freeze player
    aliases:
      - freeze
    permission: screenshare.*